#!/usr/bin/env bash
# transfer from a client to the server with bash
# Requirements
# - file path to be tranfered to server
# - server ip address to host the file transfered
# - Username that scp uses in  connecting server
# - path to the private key on the server

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
