#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo nginx start

new_string="\\\trewrite ^/redirect_me https://bit.ly/3McEZPG permanent;"

sudo sed -i "47i $new_string" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
