#!/usr/bin/env bash
# configuring nginx server to redirect missing web to created on

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "43i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
